-- The other end of a suspension record.
--
-- Reinstating used to clear `suspended_at`, `suspended_by` and
-- `suspended_reason`, so a moderation decision survived exactly until it was
-- reversed. Keeping them turned the three into "the most recent suspension",
-- which is most of the record but not the part an operator asks for: the
-- reason and the moderator are already on the row, and what is missing is
-- when the account was let back in.
--
-- Nullable with no backfill, and the null means something specific: never
-- reinstated. That covers both a row that was never suspended and one that is
-- suspended right now, which is fine because neither is a reinstatement, and
-- `status` is what distinguishes them — as it is for every other question
-- about whether somebody may act.
--
-- Rows reinstated before this migration keep a null here forever. Inventing a
-- timestamp for them would be worse than admitting the gap: it would make an
-- unrecorded event look recorded, which is the failure this column exists to
-- fix.
--
-- Cleared again by `suspendAccount`, so the four columns always describe one
-- episode. A suspension newer than the reinstatement that supposedly ended it
-- is an ordering no reader could make sense of, and it is cheaper to make it
-- unrepresentable than to explain it.

ALTER TABLE "accounts" ADD COLUMN "reinstated_at" timestamp with time zone;
