/**
 * Deployment-owned database tables.
 *
 * Re-exported from `lib/db/schema.ts`, so anything declared here reaches the
 * drizzle instance — `db.query`, the inferred row types, all of it — without
 * the platform knowing what the tables mean.
 *
 * A fork puts its own copy at `content.local/schema.ts` and keeps the matching
 * migrations in `drizzle.local/`, generated by its own drizzle-kit config. See
 * the "派生一份自己的部署" section of the README. This file is the upstream
 * fallback and declares nothing.
 */

export {};
